# Generated by Django 2.1.2 on 2020-04-25 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('streamer', models.CharField(max_length=30)),
                ('pic_path', models.CharField(max_length=150)),
                ('youtube_channel', models.CharField(max_length=50)),
                ('device1', models.CharField(max_length=30)),
                ('device1_spec', models.CharField(max_length=30)),
                ('device2', models.CharField(max_length=30)),
                ('device2_spec', models.CharField(max_length=30)),
                ('viewed_count', models.IntegerField()),
                ('gametitle', models.CharField(max_length=30)),
                ('edit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
