# Generated by Django 2.1.2 on 2020-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDevice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='viewed_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
