# Generated by Django 2.1.2 on 2020-04-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDevice', '0003_auto_20200426_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='edit_user',
            new_name='user',
        ),
    ]
