# Generated by Django 2.1.2 on 2020-04-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDevice', '0008_auto_20200426_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='youtube_channel',
            field=models.CharField(max_length=80),
        ),
    ]
