# Generated by Django 2.1.2 on 2020-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDevice', '0009_auto_20200427_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='viewed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
